name: Setup workspace
description: Checkout the repo, setup Node, and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - run: yarn --frozen-lockfile
      shell: bash
