name: Validate Pull Requests

on:
   pull_request:

jobs:
  validate:
    name: Validate Pull Request
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - id: setup
        uses: ./.github/actions/setup_workspace

      - run: yarn lint
      - run: make compile_prod

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test
